# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_userinfo_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='usertype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.UserType'),
            preserve_default=False,
        ),
    ]
