# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_userinfo_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='caption',
        ),
    ]
