# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_usertype_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='caption',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
