# Generated by Django 2.0.5 on 2018-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='os_type',
            field=models.CharField(choices=[('redhat', 'Redhat\\CentOS'), ('ubuntu', 'Ubuntu'), ('suse', 'Suse'), ('windows', 'Windows')], default='redhat', max_length=64),
        ),
    ]
